"""entries.py - Chris Fisher "cdfisher", 2023
File containing lists of the entries in the various subcategories of the
OSRS highscores for use in the highscores submodule.
"""

entries_dict = {
    'Overall': 'overall',
    'Attack': 'attack',
    'Defence': 'defence',
    'Strength': 'strength',
    'Hitpoints': 'hitpoints',
    'Ranged': 'ranged',
    'Prayer': 'prayer',
    'Magic': 'magic',
    'Cooking': 'cooking',
    'Woodcutting': 'woodcutting',
    'Fletching': 'fletching',
    'Fishing': 'fishing',
    'Firemaking': 'firemaking',
    'Crafting': 'crafting',
    'Smithing': 'smithing',
    'Mining': 'mining',
    'Herblore': 'herblore',
    'Agility': 'agility',
    'Thieving': 'thieving',
    'Slayer': 'slayer',
    'Farming': 'farming',
    'Runecraft': 'runecraft',
    'Hunter': 'hunter',
    'Construction': 'construction',
    'League Points': 'league_points',
    'Deadman Points': 'deadman_points',
    'Bounty Hunter - Hunter': 'bounty_hunter_hunter',
    'Bounty Hunter - Rogue': 'bounty_hunter_rogue',
    'Bounty Hunter (Legacy) - Hunter': 'bounty_hunter_legacy_hunter',
    'Bounty Hunter (Legacy) - Rogue': 'bounty_hunter_legacy_rogue',
    'Clue Scrolls (all)': 'clue_scrolls_all',
    'Clue Scrolls (beginner)': 'clue_scrolls_beginner',
    'Clue Scrolls (easy)': 'clue_scrolls_easy',
    'Clue Scrolls (medium)': 'clue_scrolls_medium',
    'Clue Scrolls (hard)': 'clue_scrolls_hard',
    'Clue Scrolls (elite)': 'clue_scrolls_elite',
    'Clue Scrolls (master)': 'clue_scrolls_master',
    'LMS - Rank': 'lms_rank',
    'PvP Arena - Rank': 'pvp_arena_rank',
    'Soul Wars Zeal': 'soul_wars_zeal',
    'Rifts closed': 'rifts_closed',
    'Abyssal Sire': 'abyssal_sire',
    'Alchemical Hydra': 'alchemical_hydra',
    'Artio': 'artio',
    'Barrows Chests': 'barrows_chests',
    'Bryophyta': 'bryophyta',
    'Callisto': 'callisto',
    'Calvar\'ion': 'calvar_ion',
    'Cerberus': 'cerberus',
    'Chambers of Xeric': 'chambers_of_xeric',
    'Chambers of Xeric: Challenge Mode': 'chambers_of_xeric_challenge_mode',
    'Chaos Elemental': 'chaos_elemental',
    'Chaos Fanatic': 'chaos_fanatic',
    'Commander Zilyana': 'commander_zilyana',
    'Corporeal Beast': 'corporeal_beast',
    'Crazy Archaeologist': 'crazy_archaeologist',
    'Dagannoth Prime': 'dagannoth_prime',
    'Dagannoth Rex': 'dagannoth_rex',
    'Dagannoth Supreme': 'dagannoth_supreme',
    'Deranged Archaeologist': 'deranged_archaeologist',
    'Duke Sucellus': 'duke_sucellus',
    'General Graardor': 'general_graardor',
    'Giant Mole': 'giant_mole',
    'Grotesque Guardians': 'grotesque_guardians',
    'Hespori': 'hespori',
    'Kalphite Queen': 'kalphite_queen',
    'King Black Dragon': 'king_black_dragon',
    'Kraken': 'kraken',
    'Kree\'Arra': 'kree_arra',
    'K\'ril Tsutsaroth': 'kril_tsutsaroth',
    'Mimic': 'mimic',
    'Nex': 'nex',
    'Nightmare': 'nightmare',
    'Phosani\'s Nightmare': 'phosanis_nightmare',
    'Obor': 'obor',
    'Phantom Muspah': 'phantom_muspah',
    'Sarachnis': 'sarachnis',
    'Scorpia': 'scorpia',
    'Scurrius': 'scurrius',
    'Skotizo': 'skotizo',
    'Spindel': 'spindel',
    'Tempoross': 'tempoross',
    'The Gauntlet': 'the_gauntlet',
    'The Corrupted Gauntlet': 'the_corrupted_gauntlet',
    'The Leviathan': 'the_leviathan',
    'The Whisperer': 'the_whisperer',
    'Theatre of Blood': 'theatre_of_blood',
    'Theatre of Blood: Hard Mode': 'theatre_of_blood_hard_mode',
    'Thermonuclear Smoke Devil': 'thermonuclear_smoke_devil',
    'Tombs of Amascut': 'tombs_of_amascut',
    'Tombs of Amascut: Expert Mode': 'tombs_of_amascut_expert_mode',
    'TzKal-Zuk': 'tzkal_zuk',
    'TzTok-Jad': 'tztok_jad',
    'Vardorvis': 'vardorvis',
    'Venenatis': 'venenatis',
    'Vet\'ion': 'vet_ion',
    'Vorkath': 'vorkath',
    'Wintertodt': 'wintertodt',
    'Zalcano': 'zalcano',
    'Zulrah': 'zulrah',
}

skill_attributes = [
    'overall',
    'attack',
    'defence',
    'strength',
    'hitpoints',
    'ranged',
    'prayer',
    'magic',
    'cooking',
    'woodcutting',
    'fletching',
    'fishing',
    'firemaking',
    'crafting',
    'smithing',
    'mining',
    'herblore',
    'agility',
    'thieving',
    'slayer',
    'farming',
    'runecraft',
    'hunter',
    'construction'
]

activity_attributes = [
    'league_points',
    'deadman_points',
    'bounty_hunter_hunter',
    'bounty_hunter_rogue',
    'bounty_hunter_legacy_hunter',
    'bounty_hunter_legacy_rogue',
    'clue_scrolls_all',
    'clue_scrolls_beginner',
    'clue_scrolls_easy',
    'clue_scrolls_medium',
    'clue_scrolls_hard',
    'clue_scrolls_elite',
    'clue_scrolls_master',
    'lms_rank',
    'pvp_arena_rank',
    'soul_wars_zeal',
    'rifts_closed'
]

boss_attributes = [
    'abyssal_sire',
    'alchemical_hydra',
    'artio',
    'barrows_chests',
    'bryophyta',
    'callisto',
    'calvar_ion',
    'cerberus',
    'chambers_of_xeric',
    'chambers_of_xeric_challenge_mode',
    'chaos_elemental',
    'chaos_fanatic',
    'commander_zilyana',
    'corporeal_beast',
    'crazy_archaeologist',
    'dagannoth_prime',
    'dagannoth_rex',
    'dagannoth_supreme',
    'deranged_archaeologist',
    'duke_sucellus',
    'general_graardor',
    'giant_mole',
    'grotesque_guardians',
    'hespori',
    'kalphite_queen',
    'king_black_dragon',
    'kraken',
    'kree_arra',
    'kril_tsutsaroth',
    'mimic',
    'nex',
    'nightmare',
    'phosanis_nightmare',
    'obor',
    'phantom_muspah',
    'sarachnis',
    'scorpia',
    'scurrius',
    'skotizo',
    'spindel',
    'tempoross',
    'the_gauntlet',
    'the_corrupted_gauntlet',
    'the_leviathan',
    'the_whisperer',
    'theatre_of_blood',
    'theatre_of_blood_hard_mode',
    'thermonuclear_smoke_devil',
    'tombs_of_amascut',
    'tombs_of_amascut_expert_mode',
    'tzkal_zuk',
    'tztok_jad',
    'vardorvis',
    'venenatis',
    'vet_ion',
    'vorkath',
    'wintertodt',
    'zalcano',
    'zulrah'
]

all_entries = skill_attributes + activity_attributes + boss_attributes

n_entries = len(entries_dict)

# Technically there are (this number - 1) skills since 'overall' is included but this is more practically useful for
# most use cases here
n_skills = len(skill_attributes)

n_activities = len(activity_attributes)
n_bosses = len(boss_attributes)
